import type { FederalLand } from '@/lib/types'

export const FEDERAL_LANDS: FederalLand[] = [
  // === National Park Service (NPS) ===
  {
    id: 'nps-yellowstone',
    name: 'Yellowstone National Park',
    agency: 'NPS',
    agencyName: 'National Park Service',
    state: 'WY',
    lat: 44.428,
    lng: -110.5885,
    description: 'First national park, famous for geysers, hot springs, and wildlife.',
  },
  {
    id: 'nps-yosemite',
    name: 'Yosemite National Park',
    agency: 'NPS',
    agencyName: 'National Park Service',
    state: 'CA',
    lat: 37.8651,
    lng: -119.5383,
    description: 'Iconic granite cliffs, waterfalls, and giant sequoias.',
  },
  {
    id: 'nps-grand-canyon',
    name: 'Grand Canyon National Park',
    agency: 'NPS',
    agencyName: 'National Park Service',
    state: 'AZ',
    lat: 36.1069,
    lng: -112.1129,
    description: 'Immense canyon carved by the Colorado River over millions of years.',
  },
  {
    id: 'nps-glacier',
    name: 'Glacier National Park',
    agency: 'NPS',
    agencyName: 'National Park Service',
    state: 'MT',
    lat: 48.7596,
    lng: -113.787,
    description: 'Pristine forests, alpine meadows, and glacial-carved peaks.',
  },
  {
    id: 'nps-everglades',
    name: 'Everglades National Park',
    agency: 'NPS',
    agencyName: 'National Park Service',
    state: 'FL',
    lat: 25.2866,
    lng: -80.8987,
    description: 'Largest subtropical wilderness in the United States.',
  },
  {
    id: 'nps-denali',
    name: 'Denali National Park',
    agency: 'NPS',
    agencyName: 'National Park Service',
    state: 'AK',
    lat: 63.3333,
    lng: -150.5,
    description: 'Home to North America\'s tallest peak at 20,310 feet.',
  },

  // === Bureau of Land Management (BLM) ===
  {
    id: 'blm-red-rock',
    name: 'Red Rock Canyon NCA',
    agency: 'BLM',
    agencyName: 'Bureau of Land Management',
    state: 'NV',
    lat: 36.1357,
    lng: -115.4294,
    description: 'Stunning red sandstone formations near Las Vegas.',
  },
  {
    id: 'blm-moab',
    name: 'Moab Field Office Lands',
    agency: 'BLM',
    agencyName: 'Bureau of Land Management',
    state: 'UT',
    lat: 38.5733,
    lng: -109.5498,
    description: 'World-class mountain biking, climbing, and off-road terrain.',
  },
  {
    id: 'blm-sonoran-desert',
    name: 'Sonoran Desert National Monument',
    agency: 'BLM',
    agencyName: 'Bureau of Land Management',
    state: 'AZ',
    lat: 32.8,
    lng: -112.3,
    description: 'Pristine Sonoran Desert landscape with saguaro forests.',
  },
  {
    id: 'blm-steens-mountain',
    name: 'Steens Mountain Wilderness',
    agency: 'BLM',
    agencyName: 'Bureau of Land Management',
    state: 'OR',
    lat: 42.6345,
    lng: -118.5783,
    description: 'Dramatic fault-block mountain rising nearly a mile above the Alvord Desert.',
  },
  {
    id: 'blm-rio-grande-del-norte',
    name: 'Río Grande del Norte National Monument',
    agency: 'BLM',
    agencyName: 'Bureau of Land Management',
    state: 'NM',
    lat: 36.6672,
    lng: -105.7167,
    description: 'Volcanic landscape along the Rio Grande gorge.',
  },

  // === U.S. Fish and Wildlife Service (FWS) ===
  {
    id: 'fws-arctic',
    name: 'Arctic National Wildlife Refuge',
    agency: 'FWS',
    agencyName: 'U.S. Fish and Wildlife Service',
    state: 'AK',
    lat: 69.75,
    lng: -144.0,
    description: 'America\'s largest wildlife refuge, home to caribou and polar bears.',
  },
  {
    id: 'fws-okefenokee',
    name: 'Okefenokee National Wildlife Refuge',
    agency: 'FWS',
    agencyName: 'U.S. Fish and Wildlife Service',
    state: 'GA',
    lat: 30.7413,
    lng: -82.2726,
    description: 'One of the largest intact freshwater ecosystems in North America.',
  },
  {
    id: 'fws-merritt-island',
    name: 'Merritt Island National Wildlife Refuge',
    agency: 'FWS',
    agencyName: 'U.S. Fish and Wildlife Service',
    state: 'FL',
    lat: 28.7275,
    lng: -80.7514,
    description: 'Adjacent to Kennedy Space Center, home to manatees and sea turtles.',
  },
  {
    id: 'fws-bosque-del-apache',
    name: 'Bosque del Apache NWR',
    agency: 'FWS',
    agencyName: 'U.S. Fish and Wildlife Service',
    state: 'NM',
    lat: 33.8067,
    lng: -106.8917,
    description: 'Famous for sandhill crane and snow goose migrations.',
  },

  // === Bureau of Indian Affairs (BIA) ===
  {
    id: 'bia-navajo-nation',
    name: 'Navajo Nation',
    agency: 'BIA',
    agencyName: 'Bureau of Indian Affairs',
    state: 'AZ',
    lat: 36.0672,
    lng: -109.1880,
    description: 'Largest Native American reservation, spanning AZ, UT, and NM.',
  },
  {
    id: 'bia-pine-ridge',
    name: 'Pine Ridge Reservation',
    agency: 'BIA',
    agencyName: 'Bureau of Indian Affairs',
    state: 'SD',
    lat: 43.1856,
    lng: -102.5561,
    description: 'Home of the Oglala Lakota people in the South Dakota Badlands.',
  },
  {
    id: 'bia-wind-river',
    name: 'Wind River Reservation',
    agency: 'BIA',
    agencyName: 'Bureau of Indian Affairs',
    state: 'WY',
    lat: 43.0095,
    lng: -108.7818,
    description: 'Shared by the Eastern Shoshone and Northern Arapaho tribes.',
  },
  {
    id: 'bia-flathead',
    name: 'Flathead Reservation',
    agency: 'BIA',
    agencyName: 'Bureau of Indian Affairs',
    state: 'MT',
    lat: 47.3174,
    lng: -114.0803,
    description: 'Home to the Confederated Salish and Kootenai Tribes.',
  },

  // === U.S. Forest Service (USFS) ===
  {
    id: 'usfs-tongass',
    name: 'Tongass National Forest',
    agency: 'USFS',
    agencyName: 'U.S. Forest Service',
    state: 'AK',
    lat: 57.0,
    lng: -134.0,
    description: 'Largest national forest, temperate rainforest in Southeast Alaska.',
  },
  {
    id: 'usfs-shoshone',
    name: 'Shoshone National Forest',
    agency: 'USFS',
    agencyName: 'U.S. Forest Service',
    state: 'WY',
    lat: 44.0,
    lng: -109.5,
    description: 'America\'s first national forest, adjacent to Yellowstone.',
  },
  {
    id: 'usfs-white-mountain',
    name: 'White Mountain National Forest',
    agency: 'USFS',
    agencyName: 'U.S. Forest Service',
    state: 'NH',
    lat: 44.1,
    lng: -71.5,
    description: 'Premier hiking destination with the Presidential Range.',
  },

  // === Bureau of Reclamation (USBR) ===
  {
    id: 'usbr-hoover-dam',
    name: 'Hoover Dam & Lake Mead',
    agency: 'USBR',
    agencyName: 'Bureau of Reclamation',
    state: 'NV',
    lat: 36.0161,
    lng: -114.7377,
    description: 'Iconic dam and largest reservoir in the United States.',
  },
  {
    id: 'usbr-glen-canyon',
    name: 'Glen Canyon Dam & Lake Powell',
    agency: 'USBR',
    agencyName: 'Bureau of Reclamation',
    state: 'AZ',
    lat: 36.9375,
    lng: -111.4856,
    description: 'Major Colorado River dam forming Lake Powell.',
  },
  {
    id: 'usbr-grand-coulee',
    name: 'Grand Coulee Dam',
    agency: 'USBR',
    agencyName: 'Bureau of Reclamation',
    state: 'WA',
    lat: 47.9554,
    lng: -118.9815,
    description: 'Largest hydropower producer in the United States.',
  },
]
